service: aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
profile: serverless-aws
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
